cache:
    - yarn
    - pip
    - directories:
        - /opt/python/
        - /home/travis/.local/share/

matrix:
  include:
    - language: python
      sudo: true
      python:
        - 3.6
      # command to install dependencies
      install:
      - pip install -U pip pipenv
      - pipenv install --dev
      script:
      - make test
      branches:
        only:
        - master

    - language: node_js
      dist: trusty
      sudo: true
      node_js:
        - 11
      script:
      - yarn compile
      branches:
        only:
        - master
