env: dev
namespace: dev
publicIP: false

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  name: eu.gcr.io/ons-rasrmbs-management
  pullPolicy: Always

container:
  port: 8080
service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "256Mi"

host: "0.0.0.0"
reportRefreshSeconds: 10
loggingLevel: INFO

ingress:
  enabled: false
  host: responses-dashboard.example.com
  certName: responses-dashboard-cert

dns:
  enabled: false
  wellKnownPort: 8080